# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='archive', verbose_name='Image'),
        ),
    ]
