# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20161015_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'permissions': (('delete_thread', 'Can delete board threads'),)},
        ),
    ]
