# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20160713_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boards.Board'),
            preserve_default=False,
        ),
    ]
