# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20161016_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
    ]
