# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20161017_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='picture',
            new_name='image',
        ),
    ]
